version: '2.1'
networks:
  mysql-network:

services:
  db:
    container_name: db
    image: mysql:5.7
    command: --wait-timeout=28800 --max_allowed_packet=1073741824
    environment:
      MYSQL_ROOT_PASSWORD: "123"
      MYSQL_DATABASE: "invest"
    tty: true
    ports:
      - "3306:3306"
    networks:
      - mysql-network
    healthcheck:
        test: ["CMD-SHELL", "mysqladmin ping -h localhost -p123"]
        interval: 2s
        timeout: 5s
        retries: 5
    volumes:
      - ./data:/root/data/
      - ./dump:/docker-entrypoint-initdb.d/
  spark:
    container_name: spark
    image: jupyter/all-spark-notebook:latest
    tty: true
    ports:
      - "8888:8888"
      - "4040:4040"
    networks:
      - mysql-network
    volumes:
      - ./notebooks:/home/jovyan/
      - ./modelos/:/home/jovyan/modelos/
  api:
    container_name: api
    build:
      context: ./
      dockerfile: Dockerfile-api
    ports:
      - "8000:8000"
    networks:
      - mysql-network
    depends_on:
      - "db"
