version: '2.1'
services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile-api
    container_name: api
    restart: always
    tty: true
    ports:
      - "8000:8000"
    networks:
      - mysql-network
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: db
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "123"
      MYSQL_DATABASE: "invest"
    tty: true
    ports:
      - "3306:3306"
    networks:
      - mysql-network
    healthcheck:
        test: ["CMD-SHELL", "mysqladmin ping -h localhost -p123"]
        interval: 2s
        timeout: 5s
        retries: 5



networks: 
  mysql-network:
    driver: bridge

