FROM python:3.6
RUN mkdir -p /api/scripts
RUN mkdir -p /data
WORKDIR /api/
COPY requirements.txt /api/
RUN pip install -r ./requirements.txt
COPY api/ /api
COPY scripts/ /api/scripts/
COPY data/ /data/
RUN chmod 755 /api/scripts/*.sh
ENTRYPOINT /api/scripts/startup.sh
