# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-04-04 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Predict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('idade', models.IntegerField()),
                ('perfilInvestidor', models.IntegerField()),
                ('scoreSituacaoFinanceira', models.FloatField()),
                ('scoreNivelConhecimento', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('Resultado', models.TextField()),
            ],
        ),
    ]
