# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-03-17 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Predict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataId', models.CharField(max_length=100)),
                ('ClienteId', models.CharField(max_length=100)),
                ('Idade', models.CharField(max_length=100)),
                ('EstadoCivil', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ClienteId', models.CharField(max_length=100)),
                ('Resultado', models.TextField()),
            ],
        ),
    ]
